### ISSUE TITLE
Error: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by clostermannshof** [muhlba91/onyx-homeassistant-integration#267]
Hey Daniel, since today 10:59:42 all my hella devices became unavailable and i couldn't get the integration to work since then. No changes being made as far as I can guess. See the logs attached:

`2024-12-03 13:37:21.292 ERROR (MainThread) [onyx_client.utils.response] Received erroneous HTTP response from ONYX API: 404
2024-12-03 13:37:21.293 ERROR (MainThread) [onyx_client.client] Could not call ONYX API for device 61ccec56b25a82356da0a35433fe2c390bc80153c82d8d361bbd130c: /devices.
2024-12-03 13:37:21.294 ERROR (MainThread) [custom_components.hella_onyx.api_connector] Unexpected error fetching hella_onyx data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hella_onyx/api_connector.py", line 68, in _async_update_data
    return await self.update()
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hella_onyx/api_connector.py", line 81, in update
    device_data = {device.identifier: device for device in devices}
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
2024-12-03 13:38:01.673 ERROR (MainThread) [onyx_client.utils.response] Received erroneous HTTP response from ONYX API: 404
2024-12-03 13:38:01.674 ERROR (MainThread) [onyx_client.client] Could not call ONYX API for device 61ccec56b25a82356da0a35433fe2c390bc80153c82d8d361bbd130c: /devices.
2024-12-03 13:38:01.674 ERROR (MainThread) [custom_components.hella_onyx.api_connector] Unexpected error fetching hella_onyx data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hella_onyx/api_connector.py", line 68, in _async_update_data
    return await self.update()
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hella_onyx/api_connector.py", line 81, in update
    device_data = {device.identifier: device for device in devices}
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
`

**Comment by muhlba91** [comment]
currently, i suspect this to be on Hella's side.

i have the same problem since about 11:05am, my Alexa devices can't access Onyx either, and when querying the endpoints manually, i receive a `404` error.

looking at this and the fact that the `authorize` endpoint doesn't respond either (it runs into a timeout), i suspect it might be authentication related.

a restart of the Onyx device solved at least the issue of the Onyx app not working at all but the other errors still persist. (i think the app tries to access it locally, if found?)

my plan was to raise a support ticket by end of today if the issue keeps persisting until then.

**Comment by muhlba91** [comment]
i just tried it again and it works for me.
@clostermannshof can you confirm this?

**Comment by clostermannshof** [comment]
yes I can confirm 🙏

**Comment by joseffilzmaier** [comment]
I can conform there has been a server outage on our end from around 10:20 until 20:10
We're sorry for any inconvenience that this might have caused and will work on ensuring that our API and Services are continually up and running.

**Comment by muhlba91** [comment]
thank you for this confirmation. 👍 

outages can happen, and i'm happy to hear this was solved and everything is up and running again.
